services:
  portainer:
      image: portainer/portainer-ce:${PORTAINER_VERSION}
      command:
        -H tcp://tasks.agent:9001 --tlsskipverify
        --tlscert /certs/cert.pem
        --tlskey /certs/key.pem
      ports:
        - 9443:9443
        - 9000:9000
      volumes:
        - type: bind
          source: ${DOCKER_SWARM_STORAGE}/portainer/data
          target: /data

        - type: bind
          source: ${DOCKER_SWARM_STORAGE}/portainer/certs
          target: /certs
          read_only: true
      networks:
        - network
      deploy:
        mode: replicated
        replicas: 1

  agent:
    image: portainer/agent:${PORTAINER_VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  network:
    driver: overlay
    attachable: true
